baseURL = 'http://side-realms.github.io'
publishDir = "docs"
languageCode = 'en-us'
theme = "m10c"
title = "ãŠèŒ¶ã¯ç¶¾é·¹æ´¾"
paginate = 20
buildDrafts = false
buildFuture = false
buildExpired = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "log"
    name = "log"
    url = "/log/"
    weight = 2
  [[menu.main]]
    identifier = "treasure trove"
    name = "treasure trove"
    url = "/treasure/"
    weight = 3
  [[menu.post]]
    identifier = "sound"
    name = "sound"
    url = "/sound"
    weight = 1
  [[menu.post]]
    identifier = "container"
    name = "container"
    url = "/container"
    weight = 2
  [[menu.post]]
    identifier = "writeup"
    name = "writeup"
    url = "/writeup"
    weight = 2
  [[menu.post]]
    identifier = "other"
    name = "other"
    url = "/other"
    weight = 3

[params]
  author = "KoheiDoi"
  description = "æœ€è¿‘ã¯é¢¯ã‚‚å¥½ã"
  #menu_item_separator = " ğŸ™ "
  menu_item_separator = ""
  avatar = "images/avatar.jpg"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com"

[params.style]
darkestColor = "#1b2d45"  # ã‚µã‚¤ãƒ‰ãƒãƒ¼èƒŒæ™¯
darkColor = "#001534"     # ãƒ¡ã‚¤ãƒ³èƒŒæ™¯
lightColor = "#b7c9e4"    # ãƒ•ã‚©ãƒ³ãƒˆè‰²
lightestColor = "#fffffe" # ã‚¿ã‚¤ãƒˆãƒ«
primaryColor = "#fde24f"